name: Build and deploy to Azure Web App - stockpredict-api-rslan

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install all dependencies
        working-directory: backend
        run: |
          npm install
          npm rebuild sqlite3
          pip install -r requirements.txt --target="python_packages/lib/site-packages" --no-cache-dir

      - name: Zip the deployment package
        working-directory: backend
        run: |
          zip -r deploy.zip . --exclude "*.git*"

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6C3A901C83E0475092525DD5CFF0EC20 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_68A26A0E956344E48489E01B18E2586A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_AEAF5F4840EA4718BE484B5F948537BE }}

      - name: Deploy zip to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'stockpredict-api-rslan'
          slot-name: 'Production'
          package: backend/deploy.zip
